# Generated by Django 5.1.1 on 2024-09-20 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=30)),
                ('room_image', models.ImageField(upload_to='static/img/')),
                ('desc', models.CharField(max_length=90)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminroom', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
